services:
  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]  # Проверка здоровья (если нет пароля)
      # Если используется пароль, замените на:
      # test: ["CMD", "redis-cli", "--auth", "mysecretpassword", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped    # Автоперезапуск при сбоях